"""empty message

Revision ID: 166b2e8149c8
Revises: cc4b50fd9528
Create Date: 2022-10-25 13:16:13.828111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166b2e8149c8'
down_revision = 'cc4b50fd9528'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
