"""empty message

Revision ID: 75b6c875bb19
Revises: d747a53450b0
Create Date: 2022-10-25 14:16:10.505930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b6c875bb19'
down_revision = 'd747a53450b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('married', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'married')
    # ### end Alembic commands ###
