"""empty message

Revision ID: d747a53450b0
Revises: 166b2e8149c8
Create Date: 2022-10-25 13:18:03.570003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd747a53450b0'
down_revision = '166b2e8149c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
